stages:
  prepare_data:
    cmd: python save_dataset.py
    outs:
      - data/housing.csv
  train:
    cmd: python train.py
    deps:
      - data/housing.csv
      - train.py
    outs:
      - model.pkl
