name: CI/CD ML Demo

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Run tests
        run: pytest

      - name: Deploy to GitHub Pages
        uses: streamlit/streamlit-gh-pages@v1
        with:
          app: app.py
          python-version: '3.10'

